# QUESTION NUMBER-1

https://github.com/nehrjv/Deep-Learning-lab-Assignment/tree/main

In [1]:
import numpy as np

values=([1,2,3],
[4,5,6],
[7,8,9])

print("Training input values without Bias\n", values)

Training input values without Bias
 ([1, 2, 3], [4, 5, 6], [7, 8, 9])


In [2]:
test2 = [[-1]] * len(values)
values = np.concatenate((test2, values), axis = 1)  
print("Training input values with bias in it\n",values)

Training input values with bias in it
 [[-1  1  2  3]
 [-1  4  5  6]
 [-1  7  8  9]]


In [3]:
m=4     #number of elements in each row of inputs
n=1 
weights = np.random.rand(m,n)*0.1 - 0.5
print("Initial random weights\n",weights)

Initial random weights
 [[-0.43004574]
 [-0.46543448]
 [-0.46582643]
 [-0.4729125 ]]


In [4]:
final = ([[0],[1],[1]])
print("Training data target values are\n", final)

Training data target values are
 [[0], [1], [1]]


In [5]:
def updateWeights(weights, inputs, activation, targets):
    eta = 0.25
    weights += eta*np.dot(np.transpose(inputs), targets - activation)
    return weights

In [6]:
def  prediction (inputs, weights, targets):
    #representing Activation function with 'ack [[]]' variable
    ack = [[0]] * len(inputs)
    for i in range(0, len(inputs)):    
        for j in range(0,len(weights)):
            ack[i] += inputs[i][j] * weights[j]
        ack[i] = np.where(ack[i]>0, 1, 0)
        #checking values with target
        if(targets[i] != ack[i]):
            weights = updateWeights(weights, inputs, ack[i], targets)
        print(ack[i])
    return weights

In [7]:
iterations = 4
for temp in range(0, iterations):
    print("\nIteration ",temp+1,"\n")
    weights = prediction(values, weights, final)
    
print("\nTrained Weights\n", weights)


Iteration  1 

[0]
[0]
[1]

Iteration  2 

[1]
[1]
[1]

Iteration  3 

[1]
[1]
[1]

Iteration  4 

[1]
[1]
[1]

Trained Weights
 [[-0.18004574]
 [ 1.53456552]
 [ 1.28417357]
 [ 1.0270875 ]]


In [8]:
def perceptronPredict(weights, newInput):
    activation = np.dot(newInput, weights)
    activation = np.where(activation>0, 1, 0)
    print(activation)


newInput = ([-1.0, 4,7,8])
perceptronPredict(weights, newInput)

[1]
